### ISSUE TITLE
Syntax error on node v5.0.0

### ISSUE THREAD

**Issue by roadsend** [ffxsam/meteor-mongo-sync#1]
On MacOS version 10.11.4 running Node version 5.0.0, I get the following error when attempting to run mmsync:

```
/usr/local/lib/node_modules/meteor-mongo-sync/bin/mmsync:11
let settingsFilename = '';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by ffxsam** [comment]
Nice catch! Fixed & published.
